version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: controle_produtos_backend
    volumes:
      - ./backend:/var/www
      - ./backend/php.ini:/usr/local/etc/php/php.ini
      - ./backend/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=controle_produtos
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "9000:9000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: controle_produtos_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: controle_produtos_nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./backend:/var/www
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    container_name: controle_produtos_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle_produtos
    ports:
      - "3306:3306"
    volumes:
      - dbdata_5:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: controle_produtos_redis
    ports:
      - "6379:6379"

volumes:
  dbdata_5:
